# Generated by Django 5.1.7 on 2025-08-29 12:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataBreach",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "breach_type",
                    models.CharField(
                        choices=[
                            ("confidentiality", "Confidentiality Breach"),
                            ("integrity", "Integrity Breach"),
                            ("availability", "Availability Breach"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=10,
                    ),
                ),
                ("description", models.TextField()),
                ("affected_records", models.IntegerField()),
                ("detection_date", models.DateTimeField(auto_now_add=True)),
                ("notification_required", models.BooleanField(default=True)),
                ("authority_notified", models.BooleanField(default=False)),
                ("subjects_notified", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="DataProcessingActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("purpose", models.TextField()),
                ("legal_basis", models.CharField(max_length=100)),
                ("data_categories", models.TextField()),
                ("retention_period", models.IntegerField(help_text="Days")),
                ("third_party_sharing", models.BooleanField(default=False)),
                ("cross_border_transfer", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="DataSubjectRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("access", "Data Access"),
                            ("rectification", "Data Rectification"),
                            ("erasure", "Data Erasure"),
                            ("portability", "Data Portability"),
                            ("restriction", "Processing Restriction"),
                            ("objection", "Processing Objection"),
                        ],
                        max_length=20,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("full_name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("response", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="PrivacyPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=10)),
                ("content", models.TextField()),
                ("effective_date", models.DateTimeField()),
                ("language", models.CharField(default="en", max_length=5)),
                ("is_active", models.BooleanField(default=False)),
            ],
            options={
                "unique_together": {("version", "language")},
            },
        ),
        migrations.CreateModel(
            name="ConsentRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_key", models.CharField(blank=True, max_length=40, null=True)),
                ("ip_address", models.GenericIPAddressField()),
                (
                    "consent_type",
                    models.CharField(
                        choices=[
                            ("functional", "Functional Cookies"),
                            ("analytics", "Analytics Cookies"),
                            ("marketing", "Marketing Cookies"),
                            ("data_processing", "Data Processing"),
                        ],
                        max_length=20,
                    ),
                ),
                ("consent_given", models.BooleanField(default=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("expiry_date", models.DateTimeField()),
                ("legal_basis", models.CharField(default="consent", max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "session_key", "consent_type")},
            },
        ),
    ]
